apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ibm-tech-tv-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ibm-tech-tv
spec:
  hosts:
  - "*"
  gateways:
  - ibm-tech-tv-gateway
  http:
  - match:
    - uri:
        prefix: /tv/  #this will handle the /api/
    - uri:
        prefix: /tv  #this will handle the /index.html
    rewrite:
      uri: /
    route:
    - destination:
        host: cloud-storage
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cloud-storage
spec:
  host: cloud-storage
  subsets:
  - name: v1
    labels:
      version: v1