apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: --microservices
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: csantanapr/ibm-tech-tv-storage
          context: a-cloud-storage
          docker:
            buildArgs:
              ENV: development
          sync:
            infer:
              - "**/*.js"
        - image: csantanapr/ibm-tech-tv-vision
          context: b-watson-vision
          docker:
            buildArgs:
              ENV: development
          sync:
            infer:
              - "**/*.js"
build:
  artifacts:
    - image: csantanapr/ibm-tech-tv-storage
      context: a-cloud-storage
    - image: csantanapr/ibm-tech-tv-vision
      context: b-watson-vision
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service-mesh.yaml
