apiVersion: v1
kind: Service
metadata:
  name: watson-vision
  labels:
    app: watson-vision
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer
  selector:
    app: watson-vision
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watson-vision
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/csantanapr/ibm-tech-tv
  labels:
    app: watson-vision
    app.kubernetes.io/component: watson-vision
    app.kubernetes.io/instance: watson-vision
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: watson-vision-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "14"
spec:
  selector:
    matchLabels:
      app: watson-vision
  template:
    metadata:
      labels:
        app: watson-vision
    spec:
      containers:
        - name: watson-vision
          image: csantanapr/ibm-tech-tv
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - secretRef:
                name: watson
          resources:
            requests:
              memory: "100Mi"
              cpu: "5m"
          livenessProbe:
            tcpSocket:
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
